---
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-rational-order
plugins:
  # TODO 该插件尚未支持stylelint 16.x
  - stylelint-declaration-block-no-ignored-properties
rules:
  # 禁止使用由于其他属性的原因而被忽略的属性
  plugin/declaration-block-no-ignored-properties: true
  #// 标记 CSS 规范中未知的属性-值对
  # declaration-property-value-no-unknown: true
  # 禁止空块
  block-no-empty: true
  # 在声明的块中中禁止出现重复的属性
  declaration-block-no-duplicate-properties: true
  # 颜色6位长度
  color-hex-length: long
  # 可能的情况下使用命名的颜色
  color-named: always-where-possible
  # 禁止使用无效的十六进制颜色
  color-no-invalid-hex: true
  # 特性值必须使用引号
  selector-attribute-quotes: always
  selector-class-pattern: null
  # 忽略伪类选择器 ::v-deep
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - v-deep
  # 禁止低优先级的选择器出现在高优先级的选择器之后。
  no-descending-specificity: null
  # 禁止使用重复的字体名称
  font-family-no-duplicate-names: true
  # 每一个不是关键字的字体名都使用引号括起来
  font-family-name-quotes: always-unless-keyword
  # 不验证@未知的名字，为了兼容scss的函数
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - el
        - unocss
        - variants
        - responsive
        - screen
        - function
        - if
        - each
        - include
        - mixin
  rule-empty-line-before:
    - always
    - ignore:
        - after-comment
        - first-nested
  # 禁止空注释
  comment-no-empty: true
  # 禁止使用可以缩写却不缩写的属性
  declaration-block-no-redundant-longhand-properties: true
  # 禁止缩写属性覆盖相关普通写法属性
  declaration-block-no-shorthand-property-overrides: true
  # 限制单行声明块中声明的数量
  declaration-block-single-line-max-declarations: 1
  # 禁止简写属性的冗余值
  shorthand-property-no-redundant-values: true
  # 禁止属性使用浏览器引擎前缀
  property-no-vendor-prefix: true
  # 禁止值的浏览器引擎前缀
  value-no-vendor-prefix: true
  # 禁止使用未知单位
  unit-no-unknown: true
  # 禁用 CSS 不支持的双斜线注释
  no-invalid-double-slash-comments: true
  keyframes-name-pattern: null

ignoreFiles:
  - 'static/**'
  - 'public/**'
  - '*.js'
  - '*.ts'
  - '**/*.js'
  - '**/*.ts'
  - '**/*.jsx'
  - '**/*.tsx'
  - 'src/**/*.js'
  - 'src/**/*.ts'
  - 'src/**/*.jsx'
  - 'src/**/*.tsx'
overrides:
  - files:
      - '**/*.{vue,html}'
    customSyntax: postcss-html
    rules:
      keyframes-name-pattern: null
      selector-pseudo-class-no-unknown:
        - true
        - ignorePseudoClasses:
            - deep
            - global
      selector-pseudo-element-no-unknown:
        - true
        - ignorePseudoElements:
            - v-deep
            - v-global
            - v-slotted
