/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '[...path]': (typeof import('./src/pages/[...path].vue'))['default']
    AuctionRank: (typeof import('./src/components/table/AuctionRank.vue'))['default']
    BCollapse: (typeof import('bootstrap-vue-next'))['BCollapse']
    BDropdownItem: (typeof import('bootstrap-vue-next'))['BDropdownItem']
    BNavbar: (typeof import('bootstrap-vue-next'))['BNavbar']
    BNavbarBrand: (typeof import('bootstrap-vue-next'))['BNavbarBrand']
    BNavbarNav: (typeof import('bootstrap-vue-next'))['BNavbarNav']
    BNavbarToggle: (typeof import('bootstrap-vue-next'))['BNavbarToggle']
    BNavItem: (typeof import('bootstrap-vue-next'))['BNavItem']
    BNavItemDropdown: (typeof import('bootstrap-vue-next'))['BNavItemDropdown']
    BootNav: (typeof import('./src/components/BootNav.vue'))['default']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElFooter: (typeof import('element-plus/es'))['ElFooter']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElInputNumber: (typeof import('element-plus/es'))['ElInputNumber']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
    GoodDesc: (typeof import('./src/components/GoodDesc.vue'))['default']
    ICarbonUserSpeaker: (typeof import('~icons/carbon/user-speaker'))['default']
    IIconoirGithub: (typeof import('~icons/iconoir/github'))['default']
    ILaLanguage: (typeof import('~icons/la/language'))['default']
    ILineMdEmailTwotone: (typeof import('~icons/line-md/email-twotone'))['default']
    IPhCloudMoonBold: (typeof import('~icons/ph/cloud-moon-bold'))['default']
    IPhSunHorizonBold: (typeof import('~icons/ph/sun-horizon-bold'))['default']
    ITablerBulb: (typeof import('~icons/tabler/bulb'))['default']
    Login: (typeof import('./src/pages/login.vue'))['default']
    MyAuctions: (typeof import('./src/components/table/MyAuctions.vue'))['default']
    MyGoods: (typeof import('./src/components/table/MyGoods.vue'))['default']
    Pages: (typeof import('./src/pages/index.vue'))['default']
    Register: (typeof import('./src/pages/register.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ShoppingCart: (typeof import('./src/components/table/ShoppingCart.vue'))['default']
    TheFooter: (typeof import('./src/components/TheFooter.vue'))['default']
    UserInfo: (typeof import('./src/components/UserInfo.vue'))['default']
  }
}
